name = "Sema"
grammar = "sema"
path_suffixes = ["sema"]
line_comments = ["; "]
block_comment = { start = "#|", prefix = " ", end = "|#", tab_size = 0 }

tab_size = 2
hard_tabs = false
collapsed_placeholder = "â€¦"

brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "{", end = "}", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]

autoclose_before = "])} \n\t"

word_characters = ["!", "?", "/", "-", ">", "*", "<", "#", "+", "=", ":"]
