name = "Sema"
grammar = "sema"
path_suffixes = ["sema"]
line_comments = ["; "]

tab_size = 2
hard_tabs = false

brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]

autoclose_before = "])} \n\t"

word_characters = ["!", "?", "/", "-", ">", "*", "<", "#", "+", "=", ":"]
