[package]
name = "sema-eval"
version = "1.0.0"
edition = "2021"

[dependencies]
sema-core.workspace = true
sema-reader.workspace = true
sema-stdlib.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sema-llm.workspace = true
